language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
matrix:
  include:
    # This extra job will run tests in the browser
    - node_js: 6
      env: TEST_SUITE=browser
cache:
  directories:
    - node_modules
sudo: false
install:
  - npm -g install npm@latest
  - npm install
  - npm prune
script: ./travis_tests.sh
after_success:
  - npm run coveralls
jobs:
  include:
    # stage: test runs automatically first
    - stage: npm release
      script: echo "Publishing to npm..."
      node_js: 8
      # release only main versions, not prereleases
      if: tag =~ ^v\d+\.\d+\.\d+$
      deploy:
        provider: npm
        email: engineering+npm@particle.io
        api_key:
          secure: aEFFTMYTsEAejlzTdEuMXrIgwYfITYMg051E5uBeXRh4hq4wH7bpH/RfIrVRrW/KD2S87rKVkRl5H8pfXMiBoPt5l5y05CCoXs/ZE2KsGYc1o8R/XWDKPwQuvd1FvqPHnqlZrv2rjSixvoqizM4YGHd63g5bw9oFRTQwpmc7/iJ8nYu72IdIqpVW6pV4x/VRjASGSb0sHUOP39SlEqQLCc8nhH3NHuZPhrRmJaJrlTe98511JmZ903sYT2mnAbIaiGIFszGPsy/wh34mDDfM0QVaHQAYEsaLr0HtdI6HT30uSpB9tbym102Px88n6ix/LTUNxCn9srA4vCEeLqtuof6b2xJt2zcZI2eQ22SlduWnJ1YUiVTS4AofQISN2ejO1Jb8VlT56kckVco+W+iRbhIevgBAPxYPMbW1zuS18703amhm0zO4bcKglGjIhrI/V2GmQCkJ1j0FvzQ1NOKrmt1u4C4yUsTJ/Y0QnhEymYKn1pEz5wGIUCc/1Jm7jyI5gF8syJiGcmhbWMdkWbVzu0QEorTak9i10YNFrQP3N/Kazt12+YdOhWjPBBFMnW2CluduZkzLPOXFyE9x1ZgfpKaJkCcJRTv9Cu1qssXFhMIyZiUOLTl3SOHty52jydF9AOMNG9WZM0vcHounqUBdlxwYVEigxvA3jG1NGJG4f1I=
        skip_cleanup: true
        on:
          tags: true
