language: node_js
node_js:
- 4
- 6
- 8
- 10
matrix:
  include:
  - node_js: 8
    env: TEST_SUITE=browser
cache:
  directories:
  - node_modules
sudo: false
install:
- npm -g install npm@5.10
- npm install
- npm prune
script: "./travis_tests.sh"
after_success:
- npm run coveralls
jobs:
  include:
  - stage: npm release
    script: echo "Publishing to npm..."
    node_js: 8
    if: tag =~ ^v\d+\.\d+\.\d+$
    deploy:
      provider: npm
      email: engineering+npm@particle.io
      api_key:
        secure: CalXyKGjX+NUgDG1ZUOBPIPTQVlJyWKECzhDuWtcmG8e5+7vzEAu/gjYrlOMOV6zHehWbq5ieDtA70mxfM1P+pDQBoRe6sq8Tj/wxC8pVhx/QA6JmhI0A+ipKBRtZ9EW2U5pF2J7XXg2CM1xsNUFMdz6P2xwwfJZRxl+mXUMxM2+nljbfmyNHuH4aBv/mE0gZVLHeenh5ZzRAj8GahctcrMUyrtfQAk0sbDgy6Uc3IcqZQRKQhsiqGUCKSrKxhaIZokH6vxnIo6ojkjui8cX9/bYpLvpaURKwrhsHvCnfq+EYPlMNIXvJCJ2eck7sO8lVmCvkHYmiZl6Q0Q+7dOiQkQtr9l4B1hLEnc08eZTd0MqhAAd4JR6vOI+iNAR1fhLoYjlmy0s2ZM46gyJsNYHBvFsUTqC7P6h2JRyw65W5mWo/kZPrRJ4yRauOzPpTY6sJADAZrhkfpuxqvhDljUwwpn+xLN4RWuq8TGf6hB3FTY9ICkVJerR32eiSpcKKZTRqq+GPrsf8VrAVNj0MsxUyaJOOOYkoctHIi1xhPjJjYrgwEcVaiFW9mym92rW7Jn1QeQjsJDrFkk2xOoMXI8vut4thpQLU9paS6521hJNSTJkQrv01x6dDfMwb3V4tDiFH7QP16Nf1IzL2ZJjV4O/7BijkgknwGPH4p4Gl6+hcNs=
      skip_cleanup: true
      on:
        tags: true
